In [1]:
import numpy as np

In [59]:
# Create input nodes 

class brain:
    def __init__(self, inputSize = 3, hiddenLayer=[2,2] ,outputSize = 4):
        self.inputSize = inputSize
        self.hiddenLayer = hiddenLayer
        self.outputSize = outputSize
        self.weights = []
        self.biases = []

        # Create array of X element, X = number of input nodes, 
        # each element of X contains Y sub-element, Y = numer of hidden layer nodes.
        # Weights are randomised value about normal distribution multiplied by 0.01
        self.weights.append(0.01 * np.random.randn(inputSize, hiddenLayer[0]))

        # Create array of 1 element containing Z element. Z = number of nodes in hiddenLayer 1
        # Set all biases to 0
        self.biases.append(np.zeros((1, hiddenLayer[0])))

        # Repeat for every next hiddenLayer    
        for i in range(len(hiddenLayer) - 1):
            self.weights.append(0.01 * np.random.randn(hiddenLayer[i], hiddenLayer[i+1]))
            self.biases.append(np.zeros((1, hiddenLayer[i])))

        # Repeat for Last hiddenLayer to output layer
        self.weights.append(0.01 * np.random.randn(hiddenLayer[len(hiddenLayer)-1], outputSize))
        self.biases.append(np.zeros((1, outputSize)))

    def forward(self, inputs):
        layers = [inputs]

        for i in range(len(self.weights)):
            layers.append(np.dot(layers[-1], self.weights[i]) + self.biases[i])
                          
        return layers[-1]

In [60]:
b = brain()
b.forward([1,2,3])

array([[ 3.59775158e-06, -5.00979784e-06, -4.71902598e-06,
        -1.67280425e-07]])

In [58]:
b.weights

[array([[ 0.00758943, -0.00016988],
        [-0.00227374, -0.0005487 ],
        [ 0.02822207,  0.00310799]]),
 array([[-0.0044317 , -0.01005893],
        [ 0.01347248, -0.01092822]]),
 array([[-0.00535187,  0.01035653, -0.00248091, -0.0054975 ],
        [ 0.01325831,  0.00226682, -0.0048423 , -0.00344108]])]

In [22]:
# Test layer 
inputSize = 3
hiddenLayer=[2,2]
outputSize = 4

np.random.randn(inputSize, hiddenLayer[0])

np.zeros((1, hiddenLayer[0]))

array([[0., 0.]])

In [54]:
for i in range(1):
    print(i)

len([2,2])

0


2