In [205]:
import numpy as np
import random
import os


In [148]:
# Create input nodes 

class brain:
    def __init__(self, inputSize = 3, hiddenLayer=[2,2] ,outputSize = 4):
        self.inputSize = inputSize
        self.hiddenLayer = hiddenLayer
        self.outputSize = outputSize
        self.weights = []
        self.biases = []

        # Create array of X element, X = number of input nodes, 
        # each element of X contains Y sub-element, Y = numer of hidden layer nodes.
        # Weights are randomised value about normal distribution multiplied by 0.01
        self.weights.append(0.01 * np.random.randn(inputSize, hiddenLayer[0]))

        # Create array of 1 element containing Z element. Z = number of nodes in hiddenLayer 1
        # Set all biases to 0
        self.biases.append(np.zeros((1, hiddenLayer[0])))

        # Repeat for every next hiddenLayer    
        for i in range(len(hiddenLayer) - 1):
            self.weights.append(0.01 * np.random.randn(hiddenLayer[i], hiddenLayer[i+1]))
            self.biases.append(np.zeros((1, hiddenLayer[i])))

        # Repeat for Last hiddenLayer to output layer
        self.weights.append(0.01 * np.random.randn(hiddenLayer[len(hiddenLayer)-1], outputSize))
        self.biases.append(np.zeros((1, outputSize)))

    def forward(self, inputs):
        layers = [inputs]

        for i in range(len(self.weights)):
            # layers.append(np.dot(layers[-1], self.weights[i]) + self.biases[i])
                          
        # return layers[-1]

            # hiddenOut = np.dot(layers[-1], self.weights[i]) + self.biases[i]
            # hiddenOut = np.maximum(0,hiddenOut[-1])
            # layers.append(hiddenOut)

            if i == len(self.weights) - 1:
                finalOut = np.dot(layers[-1], self.weights[i]) + self.biases[i]
                finalOut = np.maximum(0,finalOut)
                # finalOut = np.exp(layers[-1] - np.max(layers[-1], axis=1, keepdims=True))
                # finalOut = finalOut / np.sum(finalOut, axis=1, keepdims=True)
                layers.append(finalOut)

            else:
                hiddenOut = np.dot(layers[-1], self.weights[i]) + self.biases[i]
                hiddenOut = np.maximum(0,hiddenOut)
                layers.append(hiddenOut[-1])

        return layers[-1]
                
            

In [147]:
b = brain()
b.forward([1,2,3])

array([[0., 0., 0., 0.]])

In [68]:
b.weights
# len(b.weights)

[array([[-0.00546335,  0.00047544],
        [-0.00529412, -0.01119223],
        [-0.02512557, -0.0036714 ]]),
 array([[ 9.64281607e-05, -5.87221330e-03],
        [-9.92916515e-03, -1.36239665e-02]]),
 array([[-0.01389092,  0.02151274, -0.00059421, -0.00644595],
        [ 0.0052072 ,  0.01900517, -0.00141854,  0.02034631]])]

AttributeError: 'function' object has no attribute 'hiddenOut'

In [22]:
# Test layer 
inputSize = 3
hiddenLayer=[2,2]
outputSize = 4

np.random.randn(inputSize, hiddenLayer[0])

np.zeros((1, hiddenLayer[0]))

array([[0., 0.]])

In [54]:
for i in range(1):
    print(i)

len([2,2])

0


2

In [151]:
n = np.random.randint(2,size = (8,4))
n

array([[0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [1, 1, 1, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1],
       [1, 0, 1, 0]])

In [172]:
g = []
for i in range(32):
    g.append(random.randint(0,1))
str(g)


'[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]'

In [183]:
k = 0b1110
hex(k)[2]

'e'

In [528]:

# def random_hex_string(length=4):
#     return os.urandom(length).hex()

# print(random_hex_string())
r = os.urandom(1).hex()
r, int(r,16), format(int(r,16), '08b')

i = 0 
q = ''
a = ''
while i < 4:
    g = os.urandom(1).hex()
    a += g
    q += format(int(g,16), '08b')
    # q += format(int(os.urandom(1).hex(),16), '08b')
    i += 1
q, a

('10001110101101001101010011011110', '8eb4d4de')

In [459]:
format(int(os.urandom(1).hex(),16), '08b')

str

In [550]:
os.urandom(1).hex()

'e8'